source: 0
target: 1

# training settings
seed: 2020
bsize: 32
num_iters: 5000
eval_interval: 100

alpha: 0.8
T: 1.0

# optimizer
lr: 0.1
momentum: 0.9
weight_decay: 0.0005

# configurations
dataset_cfg:
    OfficeHome:
        name: OfficeHome
        path: ~/data/OfficeHome
        num_classes: 65
        domains:
                - Art
                - Clipart
                - Product
                - RealWorld
    Office31:
        name: Office31
        path: ~/data/Office31
        num_classes: 31
        domains:
                - amazon
                - dslr
                - webcam