source: 0
target: 1

# training settings
seed: 2020
bsize: 24
num_iters: 5000
eval_interval: 500

alpha: 0.8
T: 0.4

# optimizer
lr: 0.01
momentum: 0.9
weight_decay: 0.0005

# configurations
dataset_cfg:
    OfficeHome:
        name: OfficeHome
        path: /home/chu0802/data/OfficeHome
        num_classes: 65
        domains:
                - Art
                - Clipart
                - Product
                - RealWorld
    Office31:
        name: Office31
        path: /home/chu0802/data/Office31
        num_classes: 31
        domains:
                - amazon
                - dslr
                - webcam